export function mapCourseToResponse(dbCourse: any, format: 'mapped' | 'raw' = 'mapped') {
  if (!dbCourse) return null

  const mapped = {
    id: dbCourse.id,
    institutions_id: dbCourse.institutions_id,
    regulation_id: dbCourse.regulation_id,
    offering_department_id: dbCourse.offering_department_id,
    institution_code: dbCourse.institution_code,
    regulation_code: dbCourse.regulation_code,
    offering_department_code: dbCourse.offering_department_code,
    board_code: dbCourse.board_code,
    course_code: dbCourse.course_code,
    course_title: dbCourse.course_name,
    display_code: dbCourse.display_code,
    course_category: dbCourse.course_category,
    course_type: dbCourse.course_type,
    course_level: dbCourse.course_level ?? null,
    course_type_code: dbCourse.course_type_code ?? null,
    course_part_master: dbCourse.course_part_master,
    credits: dbCourse.credit ?? 0,
    split_credit: dbCourse.split_credit,
    theory_credit: dbCourse.theory_credit,
    practical_credit: dbCourse.practical_credit,
    qp_code: dbCourse.qp_code,
    e_code_name: dbCourse.e_code_name,
    exam_duration: dbCourse.exam_duration,
    evaluation_type: dbCourse.evaluation_type,
    result_type: dbCourse.result_type,
    self_study_course: dbCourse.self_study_course,
    outside_class_course: dbCourse.outside_class_course,
    open_book: dbCourse.open_book,
    online_course: dbCourse.online_course,
    dummy_number_required: !dbCourse.dummy_number_not_required,
    annual_course: dbCourse.annual_course,
    multiple_qp_set: dbCourse.multiple_qp_set,
    no_of_qp_setter: dbCourse.no_of_qp_setter,
    no_of_scrutinizer: dbCourse.no_of_scrutinizer,
    fee_exception: dbCourse.fee_exception,
    syllabus_pdf_url: dbCourse.syllabus_pdf_url,
    description: dbCourse.description,
    is_active: dbCourse.status ?? true,
    courses_status: dbCourse.courses_status ?? 'Pending',
    created_at: dbCourse.created_at,
    updated_at: dbCourse.updated_at,
    class_hours: dbCourse.class_hours ?? 0,
    theory_hours: dbCourse.theory_hours ?? 0,
    practical_hours: dbCourse.practical_hours ?? 0,
    internal_max_mark: dbCourse.internal_max_mark ?? 0,
    internal_pass_mark: dbCourse.internal_pass_mark ?? 0,
    internal_converted_mark: dbCourse.internal_converted_mark ?? 0,
    external_max_mark: dbCourse.external_max_mark ?? 0,
    external_pass_mark: dbCourse.external_pass_mark ?? 0,
    external_converted_mark: dbCourse.external_converted_mark ?? 0,
    total_pass_mark: dbCourse.total_pass_mark ?? 0,
    total_max_mark: dbCourse.total_max_mark ?? 0,
    annual_semester: dbCourse.annual_semester ?? false,
    registration_based: dbCourse.registration_based ?? false,
    credit_included: dbCourse.credit_included ?? true,
    has_hall_ticket: dbCourse.has_hall_ticket ?? true,
  }

  if (format === 'raw') {
    return {
      id: dbCourse.id,
      institutions_id: dbCourse.institutions_id,
      regulation_id: dbCourse.regulation_id,
      offering_department_id: dbCourse.offering_department_id,
      institution_code: dbCourse.institution_code,
      regulation_code: dbCourse.regulation_code,
      offering_department_code: dbCourse.offering_department_code,
      board_code: dbCourse.board_code,
      course_code: dbCourse.course_code,
      course_name: dbCourse.course_name,
      display_code: dbCourse.display_code,
      course_category: dbCourse.course_category,
      course_type: dbCourse.course_type,
      course_level: dbCourse.course_level ?? null,
      course_type_code: dbCourse.course_type_code ?? null,
      course_part_master: dbCourse.course_part_master,
      credit: dbCourse.credit,
      split_credit: dbCourse.split_credit,
      theory_credit: dbCourse.theory_credit,
      practical_credit: dbCourse.practical_credit,
      qp_code: dbCourse.qp_code,
      e_code_name: dbCourse.e_code_name,
      exam_duration: dbCourse.exam_duration,
      evaluation_type: dbCourse.evaluation_type,
      result_type: dbCourse.result_type,
      self_study_course: dbCourse.self_study_course,
      outside_class_course: dbCourse.outside_class_course,
      open_book: dbCourse.open_book,
      online_course: dbCourse.online_course,
      dummy_number_not_required: dbCourse.dummy_number_not_required,
      annual_course: dbCourse.annual_course,
      multiple_qp_set: dbCourse.multiple_qp_set,
      no_of_qp_setter: dbCourse.no_of_qp_setter,
      no_of_scrutinizer: dbCourse.no_of_scrutinizer,
      fee_exception: dbCourse.fee_exception,
      syllabus_pdf_url: dbCourse.syllabus_pdf_url,
      description: dbCourse.description,
      status: dbCourse.status,
      courses_status: dbCourse.courses_status ?? 'Pending',
      created_at: dbCourse.created_at,
      updated_at: dbCourse.updated_at,
      class_hours: dbCourse.class_hours,
      theory_hours: dbCourse.theory_hours,
      practical_hours: dbCourse.practical_hours,
      internal_max_mark: dbCourse.internal_max_mark,
      internal_pass_mark: dbCourse.internal_pass_mark,
      internal_converted_mark: dbCourse.internal_converted_mark,
      external_max_mark: dbCourse.external_max_mark,
      external_pass_mark: dbCourse.external_pass_mark,
      external_converted_mark: dbCourse.external_converted_mark,
      total_pass_mark: dbCourse.total_pass_mark,
      total_max_mark: dbCourse.total_max_mark,
      annual_semester: dbCourse.annual_semester,
      registration_based: dbCourse.registration_based,
      credit_included: dbCourse.credit_included,
      has_hall_ticket: dbCourse.has_hall_ticket,
    }
  }

  return mapped
}
