import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "@/styles/globals.css";
import { headers } from "next/headers";
import { AuthProvider } from "@/lib/auth/auth-context-parent";
import { ThemeProvider } from "@/components/common/theme-provider";
import { SessionTimeoutProvider } from "@/components/common/session-timeout-provider";
import { NonceProvider } from "@/components/common/nonce-provider";
import { CsrfFetchInterceptor } from "@/components/common/csrf-fetch-interceptor";
import { RegisterServiceWorker } from "./register-sw";
import { BugReporterWrapper } from "@/components/bug-reporter/bug-reporter-wrapper";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '500', '600'],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-space-grotesk',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "JKKN | COE",
  
  icons: {
    icon: '/jkkn_1.svg',

  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the CSP nonce generated by middleware
  const headersList = await headers()
  const cspNonce = headersList.get('x-csp-nonce') || ''

  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <head>
        {/* Performance: preconnect/dns-prefetch for auth providers */}
        <link rel="preconnect" href={process.env.NEXT_PUBLIC_PARENT_APP_URL} crossOrigin="anonymous" />
        <link rel="dns-prefetch" href={process.env.NEXT_PUBLIC_PARENT_APP_URL} />
        {/* Preconnect to Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={`${spaceGrotesk.className} ${inter.variable} ${spaceGrotesk.variable} antialiased`} suppressHydrationWarning>
        <CsrfFetchInterceptor />
        <RegisterServiceWorker />
        <NonceProvider nonce={cspNonce}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <AuthProvider autoValidate={false}>
              <BugReporterWrapper>
                <SessionTimeoutProvider
                  timeoutDuration={15} // 15 minutes
                  warningDuration={2} // 2 minutes warning
                >
                  {children}
                </SessionTimeoutProvider>
              </BugReporterWrapper>
            </AuthProvider>
          </ThemeProvider>
        </NonceProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
