-- =====================================================
-- BUNDLE NUMBERS TABLE
-- Created: 2026-05-04
-- Description: Maintains a board-wise running bundle number
--              per (institution, examination session, course).
--              Numbers are generated by the Answer Sheet Packets
--              page (Bundle Numbers tab) using the same sort order
--              as the Board Wise Regular/Arrear Count report:
--              board_order -> semester -> course_order -> course_code.
-- =====================================================

-- =====================================================
-- 1. CREATE TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.bundle_numbers (
	id uuid NOT NULL DEFAULT gen_random_uuid(),
	institutions_id uuid NOT NULL,
	examination_session_id uuid NOT NULL,
	course_id uuid NOT NULL,
	bundle_number integer NOT NULL,
	is_active boolean NULL DEFAULT true,
	remarks text NULL,
	created_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP,
	created_by uuid NULL,
	updated_by uuid NULL,

	CONSTRAINT bundle_numbers_pkey PRIMARY KEY (id),
	CONSTRAINT bundle_numbers_unique_course UNIQUE (
		institutions_id,
		examination_session_id,
		course_id
	),
	CONSTRAINT bundle_numbers_unique_number UNIQUE (
		institutions_id,
		examination_session_id,
		bundle_number
	),
	CONSTRAINT bundle_numbers_institutions_id_fkey FOREIGN KEY (institutions_id)
		REFERENCES public.institutions (id) ON DELETE CASCADE,
	CONSTRAINT bundle_numbers_examination_session_id_fkey FOREIGN KEY (examination_session_id)
		REFERENCES public.examination_sessions (id) ON DELETE CASCADE,
	CONSTRAINT bundle_numbers_course_id_fkey FOREIGN KEY (course_id)
		REFERENCES public.courses (id) ON DELETE RESTRICT,
	CONSTRAINT bundle_numbers_created_by_fkey FOREIGN KEY (created_by)
		REFERENCES public.users (id) ON DELETE SET NULL,
	CONSTRAINT bundle_numbers_updated_by_fkey FOREIGN KEY (updated_by)
		REFERENCES public.users (id) ON DELETE SET NULL,
	CONSTRAINT bundle_numbers_positive CHECK (bundle_number > 0)
) TABLESPACE pg_default;

-- =====================================================
-- 2. CREATE INDEXES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_bundle_numbers_institution
	ON public.bundle_numbers USING btree (institutions_id);

CREATE INDEX IF NOT EXISTS idx_bundle_numbers_session
	ON public.bundle_numbers USING btree (examination_session_id);

CREATE INDEX IF NOT EXISTS idx_bundle_numbers_course
	ON public.bundle_numbers USING btree (course_id);

CREATE INDEX IF NOT EXISTS idx_bundle_numbers_session_inst
	ON public.bundle_numbers USING btree (institutions_id, examination_session_id);

CREATE INDEX IF NOT EXISTS idx_bundle_numbers_active
	ON public.bundle_numbers USING btree (is_active);

-- =====================================================
-- 3. ENABLE ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE public.bundle_numbers ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- 4. CREATE RLS POLICIES
-- =====================================================

CREATE POLICY "Authenticated users can read bundle numbers"
	ON public.bundle_numbers
	FOR SELECT
	TO authenticated
	USING (true);

CREATE POLICY "Authenticated users can insert bundle numbers"
	ON public.bundle_numbers
	FOR INSERT
	TO authenticated
	WITH CHECK (true);

CREATE POLICY "Authenticated users can update bundle numbers"
	ON public.bundle_numbers
	FOR UPDATE
	TO authenticated
	USING (true)
	WITH CHECK (true);

CREATE POLICY "Admins can delete bundle numbers"
	ON public.bundle_numbers
	FOR DELETE
	TO authenticated
	USING (
		EXISTS (
			SELECT 1 FROM public.user_roles ur
			JOIN public.roles r ON ur.role_id = r.id
			WHERE ur.user_id = auth.uid()
				AND r.name IN ('admin', 'super_admin', 'coe_admin')
				AND ur.is_active = true
		)
	);

CREATE POLICY "Service role can manage all bundle numbers"
	ON public.bundle_numbers
	FOR ALL
	TO service_role
	USING (true)
	WITH CHECK (true);

-- =====================================================
-- 5. TRIGGER: updated_at
-- =====================================================

CREATE OR REPLACE FUNCTION update_bundle_numbers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_bundle_numbers_updated_at ON public.bundle_numbers;
CREATE TRIGGER trigger_update_bundle_numbers_updated_at
	BEFORE UPDATE ON public.bundle_numbers
	FOR EACH ROW
	EXECUTE FUNCTION update_bundle_numbers_updated_at();

-- =====================================================
-- 6. VIEW: bundle_numbers_detail_view
-- =====================================================

CREATE OR REPLACE VIEW public.bundle_numbers_detail_view AS
SELECT
	bn.id,
	bn.bundle_number,
	bn.is_active,
	bn.remarks,
	bn.created_at,
	bn.updated_at,

	-- Institution
	bn.institutions_id,
	i.institution_code,
	i.name AS institution_name,

	-- Examination Session
	bn.examination_session_id,
	es.session_code,
	es.session_name,

	-- Course
	bn.course_id,
	c.course_code,
	c.course_name,
	c.course_category,
	c.board_code,
	c.board_id,
	b.board_name,
	b.board_order,

	-- Created/Updated By
	cu.full_name AS created_by_name,
	uu.full_name AS updated_by_name,
	bn.created_by,
	bn.updated_by
FROM public.bundle_numbers bn
LEFT JOIN public.institutions i ON bn.institutions_id = i.id
LEFT JOIN public.examination_sessions es ON bn.examination_session_id = es.id
LEFT JOIN public.courses c ON bn.course_id = c.id
LEFT JOIN public.board b ON c.board_id = b.id
LEFT JOIN public.users cu ON bn.created_by = cu.id
LEFT JOIN public.users uu ON bn.updated_by = uu.id;

-- =====================================================
-- 7. COMMENTS
-- =====================================================

COMMENT ON TABLE public.bundle_numbers IS
	'Board-wise running bundle number per (institution, examination_session, course). Generated from the Answer Sheet Packets > Bundle Numbers tab.';
COMMENT ON COLUMN public.bundle_numbers.bundle_number IS
	'Sequential bundle number assigned in board-wise sort order (board_order -> semester -> course_order -> course_code), starting from a user-supplied start value.';

-- =====================================================
-- END OF MIGRATION
-- =====================================================
