// GENERATED by scripts/generate-api-policy.cjs — do not edit by hand.
//
// One rule per API route: the permissions of the screens that call it
// (lib/navigation-data.ts). Holding any one is enough. Re-run the script
// after adding a screen or a route, and review the diff.

import type { ApiPolicyRule } from '@/lib/auth/api-policy'

export const GENERATED_API_POLICY: readonly ApiPolicyRule[] = [
	// /exam-management/examiners/internal
	{ prefix: '/api/api-management/staff', exact: true, anyOf: ['page.exam_management.examiners.internal.view'] },
	// /bos/compositions
	{ prefix: '/api/bos/compositions', exact: true, anyOf: ['page.master.boards.view'] },
	// /bos/compositions/[id]
	{ prefix: '/api/bos/compositions/*', exact: true, anyOf: ['page.master.boards.view'] },
	// /bos/ta-da-rates
	{ prefix: '/api/bos/ta-da-rates', exact: true, anyOf: ['page.master.boards.view'] },
	// /dashboard, /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar', exact: true, anyOf: ['page.dashboard.view', 'page.pre_exam.coe_calendar.view'] },
	// /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar/*', exact: true, anyOf: ['page.pre_exam.coe_calendar.view'] },
	// /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar/bulk-upload', exact: true, anyOf: ['page.pre_exam.coe_calendar.view'] },
	// /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar/categories', exact: true, anyOf: ['page.pre_exam.coe_calendar.view'] },
	// /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar/categories/*', exact: true, anyOf: ['page.pre_exam.coe_calendar.view'] },
	// /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar/export', exact: true, anyOf: ['page.pre_exam.coe_calendar.view'] },
	// /pre-exam/coe-calendar
	{ prefix: '/api/coe-calendar/template', exact: true, anyOf: ['page.pre_exam.coe_calendar.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /course-management/course-offering, +3 more
	{ prefix: '/api/course-management/course-mapping', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_registrations.view'] },
	// /course-management/course-mapping-index, /course-management/course-mapping/add, /course-management/course-mapping/edit
	{ prefix: '/api/course-management/course-mapping/groups', exact: true, anyOf: ['page.course_management.course_mapping_index.view'] },
	// /course-management/course-mapping-index, /course-management/course-mapping/add, /course-management/course-mapping/edit
	{ prefix: '/api/course-management/course-mapping/report', exact: true, anyOf: ['page.course_management.course_mapping_index.view'] },
	// /course-management/course-mapping/add, /course-management/course-mapping/edit
	{ prefix: '/api/course-management/course-mapping/template-data', exact: true, anyOf: ['page.course_management.course_mapping_index.view'] },
	// /course-management/course-offering, /course-management/course-offering/program-wise, /exam-management/exam-applications, /exam-management/exam-applications/bulk, +6 more
	{ prefix: '/api/course-management/course-offering', exact: true, anyOf: ['page.course_management.course_offering.view', 'page.exam_management.exam_applications.bulk.view', 'page.exam_management.exam_applications.view', 'page.exam_management.exam_registrations.lookup.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.exam_timetables.view'] },
	// /course-management/course-offering, /course-management/course-offering/create
	{ prefix: '/api/course-management/course-offering/bulk-create', exact: true, anyOf: ['page.course_management.course_offering.view'] },
	// /course-management/course-offering
	{ prefix: '/api/course-management/course-offering/bulk-import', exact: true, anyOf: ['page.course_management.course_offering.view'] },
	// /course-management/course-offering, /course-management/course-offering/create, /exam-management/exam-registrations/bulk-create
	{ prefix: '/api/course-management/course-offering/lookups', exact: true, anyOf: ['page.course_management.course_offering.view', 'page.exam_management.exam_registrations.view'] },
	// /dashboard
	{ prefix: '/api/dashboard/stats', exact: true, anyOf: ['page.dashboard.view'] },
	// /exam-management/attendance-correction
	{ prefix: '/api/exam-management/attendance-correction', exact: true, anyOf: ['page.exam_management.attendance_correction.view'] },
	// /exam-management/attendance-correction
	{ prefix: '/api/exam-management/attendance-correction/courses', exact: true, anyOf: ['page.exam_management.attendance_correction.view'] },
	// /exam-management/attendance-correction
	{ prefix: '/api/exam-management/attendance-correction/sessions', exact: true, anyOf: ['page.exam_management.attendance_correction.view'] },
	// /exam-management/exam-applications
	{ prefix: '/api/exam-management/exam-applications/arrear-learners', exact: true, anyOf: ['page.exam_management.exam_applications.view'] },
	// /exam-management/exam-applications, /exam-management/exam-applications/bulk
	{ prefix: '/api/exam-management/exam-applications/bulk', exact: true, anyOf: ['page.exam_management.exam_applications.bulk.view', 'page.exam_management.exam_applications.view'] },
	// /exam-management/exam-applications, /exam-management/exam-applications/bulk
	{ prefix: '/api/exam-management/exam-applications/bulk/learner-courses', exact: true, anyOf: ['page.exam_management.exam_applications.bulk.view', 'page.exam_management.exam_applications.view'] },
	// /exam-management/exam-applications, /exam-management/exam-applications/bulk
	{ prefix: '/api/exam-management/exam-applications/bulk/subject-candidates', exact: true, anyOf: ['page.exam_management.exam_applications.bulk.view', 'page.exam_management.exam_applications.view'] },
	// /exam-management/exam-applications
	{ prefix: '/api/exam-management/exam-applications/current-papers', exact: true, anyOf: ['page.exam_management.exam_applications.view'] },
	// /exam-management/exam-attendance
	{ prefix: '/api/exam-management/exam-attendance', exact: true, anyOf: ['page.exam_management.exam_attendance.view'] },
	// /exam-management/reports/attendance
	{ prefix: '/api/exam-management/exam-attendance/absent-list', exact: true, anyOf: ['page.exam_management.reports.attendance.view'] },
	// /exam-management/reports/attendance
	{ prefix: '/api/exam-management/exam-attendance/bundle-cover', exact: true, anyOf: ['page.exam_management.reports.attendance.view'] },
	// /exam-management/exam-attendance, /exam-management/reports/attendance, /exam-management/reports/course-count, /grading/consolidated-marksheet, +4 more
	{ prefix: '/api/exam-management/exam-attendance/dropdowns', exact: true, anyOf: ['page.exam_management.exam_attendance.view', 'page.exam_management.reports.attendance.view', 'page.exam_management.reports.course_count.view', 'page.grading.semester_results.view', 'page.pre_exam.exam_attendance_sheet.view', 'page.reports.nad.view', 'page.reports.semester_marksheet.view'] },
	// /exam-management/reports/attendance
	{ prefix: '/api/exam-management/exam-attendance/report', exact: true, anyOf: ['page.exam_management.reports.attendance.view'] },
	// /exam-management/reports/attendance
	{ prefix: '/api/exam-management/exam-attendance/student-sheet', exact: true, anyOf: ['page.exam_management.reports.attendance.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/course-wise, /exam-management/exam-registrations/learner-wise, /exam-management/exam-registrations/lookup, +3 more
	{ prefix: '/api/exam-management/exam-registrations', exact: true, anyOf: ['page.exam_management.exam_registrations.lookup.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.exam_timetables.view', 'page.revaluation_management.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/approvals
	{ prefix: '/api/exam-management/exam-registrations/approvals', exact: true, anyOf: ['page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/bulk-create
	{ prefix: '/api/exam-management/exam-registrations/bulk-create', exact: true, anyOf: ['page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/bulk-create
	{ prefix: '/api/exam-management/exam-registrations/bulk-create/active-semesters', exact: true, anyOf: ['page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/bulk-create
	{ prefix: '/api/exam-management/exam-registrations/bulk-create/eligible-learners', exact: true, anyOf: ['page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/bulk-create
	{ prefix: '/api/exam-management/exam-registrations/bulk-create/lookups', exact: true, anyOf: ['page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/lookup
	{ prefix: '/api/exam-management/exam-registrations/lookup', exact: true, anyOf: ['page.exam_management.exam_registrations.lookup.view', 'page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/lookup
	{ prefix: '/api/exam-management/exam-registrations/reassign', exact: true, anyOf: ['page.exam_management.exam_registrations.lookup.view', 'page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-registrations
	{ prefix: '/api/exam-management/exam-registrations/sync-learners', exact: true, anyOf: ['page.exam_management.exam_registrations.view'] },
	// /exam-management/exam-rooms
	{ prefix: '/api/exam-management/exam-rooms', exact: true, anyOf: ['page.exam_management.exam_rooms.view'] },
	// /exam-management/exam-timetable, /exam-management/exam-timetables
	{ prefix: '/api/exam-management/exam-timetables', exact: true, anyOf: ['page.exam_management.exam_timetables.view'] },
	// /exam-management/exam-timetable, /exam-management/exam-timetables
	{ prefix: '/api/exam-management/exam-timetables/applied-subjects', exact: true, anyOf: ['page.exam_management.exam_timetables.view'] },
	// /exam-management/exam-timetable, /exam-management/exam-timetables
	{ prefix: '/api/exam-management/exam-timetables/courses-by-date', exact: true, anyOf: ['page.exam_management.exam_timetables.view'] },
	// /exam-management/exam-timetable, /exam-management/exam-timetables, /exam-management/exam-timetables/schedule
	{ prefix: '/api/exam-management/exam-timetables/schedule', exact: true, anyOf: ['page.exam_management.exam_timetables.view'] },
	// /exam-management/exam-timetables, /exam-management/exam-timetables/schedule
	{ prefix: '/api/exam-management/exam-timetables/schedule/precheck', exact: true, anyOf: ['page.exam_management.exam_timetables.view'] },
	// /exam-management/exam-timetable, /exam-management/exam-timetables
	{ prefix: '/api/exam-management/exam-timetables/upload-precheck', exact: true, anyOf: ['page.exam_management.exam_timetables.view'] },
	// /exam-management/exam-types, /exam-management/examination-sessions, /pre-exam/hall-tickets
	{ prefix: '/api/exam-management/exam-types', exact: true, anyOf: ['page.exam_management.exam_types.view', 'page.exam_management.examination_sessions.view', 'page.pre_exam.hall_tickets.view'] },
	// /exam-management/practical-attendance
	{ prefix: '/api/exam-management/practical-attendance', exact: true, anyOf: ['page.exam_management.practical_attendance.view'] },
	// /exam-management/practical-attendance
	{ prefix: '/api/exam-management/practical-attendance/dropdowns', exact: true, anyOf: ['page.exam_management.practical_attendance.view'] },
	// /exam-management/reports/course-count
	{ prefix: '/api/exam-management/reports/course-count', exact: true, anyOf: ['page.exam_management.reports.course_count.view'] },
	// /exam-management/exam-timetable, /exam-management/validate-timetable
	{ prefix: '/api/exam-management/validate-timetable', exact: true, anyOf: ['page.exam_management.exam_timetables.view', 'page.exam_management.validate_timetable.view'] },
	// /pre-exam/question-papers, /revaluation-management, /revaluation-management/create
	{ prefix: '/api/examination-sessions', exact: true, anyOf: ['page.pre_exam.question_papers.view', 'page.revaluation_management.view'] },
	// /exam-management/examiners
	{ prefix: '/api/examiner-form-configs', exact: true, anyOf: ['page.exam_management.examiners.view'] },
	// /exam-management/examiners, /exam-management/examiners/send-email, /revaluation-management
	{ prefix: '/api/examiners', exact: true, anyOf: ['page.exam_management.examiners.send_email.view', 'page.exam_management.examiners.view', 'page.revaluation_management.view'] },
	// /exam-management/examiners, /exam-management/examiners/send-email, /revaluation-management
	{ prefix: '/api/examiners/*', exact: true, anyOf: ['page.exam_management.examiners.send_email.view', 'page.exam_management.examiners.view', 'page.revaluation_management.view'] },
	// /exam-management/examiners, /exam-management/examiners/send-email, /revaluation-management
	{ prefix: '/api/examiners/send-appointment', exact: true, anyOf: ['page.exam_management.examiners.send_email.view', 'page.exam_management.examiners.view', 'page.revaluation_management.view'] },
	// /fee-details, /fee-details/create, /pre-exam/qp-examiner-assignment
	{ prefix: '/api/fee-details', exact: true, anyOf: ['page.exam_management.exam_registration_final_approval.view', 'page.pre_exam.qp_examiner_assignment.view'] },
	// /fee-details, /fee-details/create
	{ prefix: '/api/fee-details/program-levels', exact: true, anyOf: ['page.exam_management.exam_registration_final_approval.view'] },
	// /users/learner
	{ prefix: '/api/filters/departments', exact: true, anyOf: ['page.users.learners_myjkkn.view'] },
	// /users/learner
	{ prefix: '/api/filters/institutions', exact: true, anyOf: ['page.users.learners_myjkkn.view'] },
	// /reports/exam-registration-reports, /users/learner
	{ prefix: '/api/filters/programs', exact: true, anyOf: ['page.reports.exam_registration_reports.view', 'page.users.learners_myjkkn.view'] },
	// /grading/galley-report/all-clear
	{ prefix: '/api/grading/all-clear-report', exact: true, anyOf: ['page.grading.galley_report.report.view'] },
	// /grading/learner-backlogs
	{ prefix: '/api/grading/current-arrears', exact: true, anyOf: ['page.grading.learner_backlogs.view'] },
	// /grading/curriculum-grade-system
	{ prefix: '/api/grading/curriculum-grade-system', exact: true, anyOf: ['page.grading.grade_system.view'] },
	// /grading/curriculum-grade-system, /grading/curriculum-grades
	{ prefix: '/api/grading/curriculum-grades', exact: true, anyOf: ['page.grading.grade_system.view', 'page.grading.grades.view'] },
	// /grading/generate-final-marks, /grading/learner-backlogs, /grading/semester-results, /grading/test-gpa-cgpa, +1 more
	{ prefix: '/api/grading/final-marks', exact: true, anyOf: ['page.grading.generate_final_marks.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.grading.test_gpa_workflow.view', 'page.revaluation_management.view'] },
	// /grading/generate-final-marks, /grading/learner-backlogs, /grading/semester-results
	{ prefix: '/api/grading/final-marks/revaluation', exact: true, anyOf: ['page.grading.generate_final_marks.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view'] },
	// /grading/galley-report/report, /reports/nad, /result/dashboard
	{ prefix: '/api/grading/galley-report', exact: true, anyOf: ['page.grading.galley_report.report.view', 'page.reports.nad.view', 'page.result.dashboard.view'] },
	// /grading/curriculum-grade-system, /grading/grade-system, /grading/test-gpa-cgpa, /post-exam/result-release
	{ prefix: '/api/grading/grade-system', exact: true, anyOf: ['page.grading.grade_system.view', 'page.grading.semester_results.view', 'page.grading.test_gpa_workflow.view'] },
	// /grading/curriculum-grade-system, /grading/grade-system, /grading/grades, /marks-management/comment-grades
	{ prefix: '/api/grading/grades', exact: true, anyOf: ['page.grading.grade_system.view', 'page.grading.grades.view', 'page.marks_management.comment_grades.view'] },
	// /grading/galley-report/all-clear, /grading/galley-report/pass-percentage
	{ prefix: '/api/grading/pass-percentage-report', exact: true, anyOf: ['page.grading.galley_report.report.view'] },
	// /grading/learner-backlogs, /grading/semester-results, /grading/test-gpa-cgpa
	{ prefix: '/api/grading/semester-results', exact: true, anyOf: ['page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.grading.test_gpa_workflow.view'] },
	// /pre-exam/internal-mark-setting, /pre-exam/internal-mark-setting/course-associations, /pre-exam/internal-mark-setting/eligibility-rules, /pre-exam/internal-mark-setting/passing-rules, +1 more
	{ prefix: '/api/internal-assessment-patterns', exact: true, anyOf: ['page.pre_exam.internal_mark_setting.course_associations.view', 'page.pre_exam.internal_mark_setting.eligibility_rules.view', 'page.pre_exam.internal_mark_setting.passing_rules.view', 'page.pre_exam.internal_mark_setting.program_associations.view', 'page.pre_exam.internal_mark_setting.view'] },
	// /pre-exam/internal-mark-setting, /pre-exam/internal-mark-setting/course-associations, /pre-exam/internal-mark-setting/eligibility-rules, /pre-exam/internal-mark-setting/passing-rules, +1 more
	{ prefix: '/api/internal-assessment-patterns/components', exact: true, anyOf: ['page.pre_exam.internal_mark_setting.course_associations.view', 'page.pre_exam.internal_mark_setting.eligibility_rules.view', 'page.pre_exam.internal_mark_setting.passing_rules.view', 'page.pre_exam.internal_mark_setting.program_associations.view', 'page.pre_exam.internal_mark_setting.view'] },
	// /pre-exam/internal-mark-setting, /pre-exam/internal-mark-setting/course-associations, /pre-exam/internal-mark-setting/eligibility-rules, /pre-exam/internal-mark-setting/passing-rules, +1 more
	{ prefix: '/api/internal-assessment-patterns/course-associations', exact: true, anyOf: ['page.pre_exam.internal_mark_setting.course_associations.view', 'page.pre_exam.internal_mark_setting.eligibility_rules.view', 'page.pre_exam.internal_mark_setting.passing_rules.view', 'page.pre_exam.internal_mark_setting.program_associations.view', 'page.pre_exam.internal_mark_setting.view'] },
	// /pre-exam/internal-mark-setting, /pre-exam/internal-mark-setting/course-associations, /pre-exam/internal-mark-setting/eligibility-rules, /pre-exam/internal-mark-setting/passing-rules, +1 more
	{ prefix: '/api/internal-assessment-patterns/eligibility-rules', exact: true, anyOf: ['page.pre_exam.internal_mark_setting.course_associations.view', 'page.pre_exam.internal_mark_setting.eligibility_rules.view', 'page.pre_exam.internal_mark_setting.passing_rules.view', 'page.pre_exam.internal_mark_setting.program_associations.view', 'page.pre_exam.internal_mark_setting.view'] },
	// /pre-exam/internal-mark-setting, /pre-exam/internal-mark-setting/course-associations, /pre-exam/internal-mark-setting/eligibility-rules, /pre-exam/internal-mark-setting/passing-rules, +1 more
	{ prefix: '/api/internal-assessment-patterns/passing-rules', exact: true, anyOf: ['page.pre_exam.internal_mark_setting.course_associations.view', 'page.pre_exam.internal_mark_setting.eligibility_rules.view', 'page.pre_exam.internal_mark_setting.passing_rules.view', 'page.pre_exam.internal_mark_setting.program_associations.view', 'page.pre_exam.internal_mark_setting.view'] },
	// /pre-exam/internal-mark-setting, /pre-exam/internal-mark-setting/course-associations, /pre-exam/internal-mark-setting/eligibility-rules, /pre-exam/internal-mark-setting/passing-rules, +1 more
	{ prefix: '/api/internal-assessment-patterns/program-associations', exact: true, anyOf: ['page.pre_exam.internal_mark_setting.course_associations.view', 'page.pre_exam.internal_mark_setting.eligibility_rules.view', 'page.pre_exam.internal_mark_setting.passing_rules.view', 'page.pre_exam.internal_mark_setting.program_associations.view', 'page.pre_exam.internal_mark_setting.view'] },
	// /learners/directory
	{ prefix: '/api/learners/directory', exact: true, anyOf: ['page.users.learners_myjkkn.view'] },
	// /learners/discontinued-learners
	{ prefix: '/api/learners/discontinued-learners', exact: true, anyOf: ['page.users.discontinued_learners.view'] },
	// /learners/generate-register-number
	{ prefix: '/api/learners/register-numbers/generate', exact: true, anyOf: ['page.users.generate_register_number.view'] },
	// /learners/generate-register-number
	{ prefix: '/api/learners/register-numbers/lookups', exact: true, anyOf: ['page.users.generate_register_number.view'] },
	// /learners/student-strength
	{ prefix: '/api/learners/student-strength', exact: true, anyOf: ['page.reports.pre_exam.student_strength.view'] },
	// /marks-management/comment-grades
	{ prefix: '/api/marks/comment-grades', exact: true, anyOf: ['page.marks_management.comment_grades.view'] },
	// /marks-management/credit-entry
	{ prefix: '/api/marks/credit-entry', exact: true, anyOf: ['page.marks_management.credit_entry.view'] },
	// /marks-management/status-grades
	{ prefix: '/api/marks/status-grades', exact: true, anyOf: ['page.marks_management.comment_grades.view'] },
	// /marks-management/status-grades
	{ prefix: '/api/marks/status-grades/export', exact: true, anyOf: ['page.marks_management.comment_grades.view'] },
	// /marks-management/status-grades
	{ prefix: '/api/marks/status-grades/import', exact: true, anyOf: ['page.marks_management.comment_grades.view'] },
	// /master/academic-years, /users/learners-list
	{ prefix: '/api/master/academic-years', exact: true, anyOf: ['page.master.academic_years.view', 'page.users.learners_myjkkn.view'] },
	// /course-management/course-mapping, /master/batches
	{ prefix: '/api/master/batches', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.master.batches.view'] },
	// /master/batches
	{ prefix: '/api/master/batches/*', exact: true, anyOf: ['page.master.batches.view'] },
	// /exam-management/exam-timetable, /exam-management/examiners, /exam-management/examiners/send-email, /master/boards, +4 more
	{ prefix: '/api/master/boards', exact: true, anyOf: ['page.exam_management.exam_timetables.view', 'page.exam_management.examiners.send_email.view', 'page.exam_management.examiners.view', 'page.master.boards.view', 'page.master.courses.view', 'page.post_exam.answer_sheet_packets.view', 'page.pre_exam.question_papers.view', 'page.reports.dummy_numbers.view'] },
	// /master/courses
	{ prefix: '/api/master/course-info', exact: true, anyOf: ['page.master.courses.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /exam-management/exam-timetables, +3 more
	{ prefix: '/api/master/courses', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.exam_management.exam_timetables.view', 'page.master.courses.view', 'page.master.degrees.view', 'page.post_exam.answer_sheet_packets.view'] },
	// /master/courses, /post-exam/answer-sheet-packets
	{ prefix: '/api/master/courses/*', exact: true, anyOf: ['page.master.courses.view', 'page.post_exam.answer_sheet_packets.view'] },
	// /master/courses, /post-exam/answer-sheet-packets
	{ prefix: '/api/master/courses/template', exact: true, anyOf: ['page.master.courses.view', 'page.post_exam.answer_sheet_packets.view'] },
	// /master/degrees, /master/programs, /users/learners-list
	{ prefix: '/api/master/degrees', exact: true, anyOf: ['page.master.degrees.view', 'page.master.programs_myjkkn.view', 'page.users.learners_myjkkn.view'] },
	// /master/courses, /master/departments, /master/programs, /users/learners-list
	{ prefix: '/api/master/departments', exact: true, anyOf: ['page.master.courses.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.users.learners_myjkkn.view'] },
	// /course-management/course-offering/create, /exam-management/exam-rooms, /exam-management/examination-sessions, /exam-management/validate-timetable, +6 more
	{ prefix: '/api/master/institutions/*', exact: true, methods: ['GET'], anyOf: ['page.course_management.course_offering.view', 'page.exam_management.exam_rooms.view', 'page.exam_management.examination_sessions.view', 'page.exam_management.validate_timetable.view', 'page.master.institutions.view', 'page.pre_exam.hall_tickets.view', 'page.reports.exam_registration_reports.view', 'page.reports.marksheet_distribution.view', 'page.users.discontinued_learners.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /course-management/course-offering, +5 more
	{ prefix: '/api/master/programs', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_timetables.view', 'page.master.programs_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.pre_exam.coe_calendar.view', 'page.users.learners_myjkkn.view'] },
	// /course-management/course-offering/program-wise, /exam-management/exam-registrations/bulk-create, /exam-management/exam-registrations/program-wise, /fee-details, +2 more
	{ prefix: '/api/master/programs-cache', exact: true, anyOf: ['page.course_management.course_offering.view', 'page.exam_management.exam_registration_final_approval.view', 'page.exam_management.exam_registrations.view', 'page.pre_exam.question_papers.view'] },
	// /master/programs, /pre-exam/coe-calendar
	{ prefix: '/api/master/programs/*', exact: true, anyOf: ['page.master.programs_myjkkn.view', 'page.pre_exam.coe_calendar.view'] },
	// /course-management/course-mapping/edit, /master/regulations, /master/regulations/add
	{ prefix: '/api/master/regulations', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.master.regulations_myjkkn.view'] },
	// /master/regulations, /master/regulations/edit/[id]
	{ prefix: '/api/master/regulations/*', exact: true, anyOf: ['page.master.regulations_myjkkn.view'] },
	// /master/sections, /users/learners-list
	{ prefix: '/api/master/sections', exact: true, anyOf: ['page.master.sections.view', 'page.users.learners_myjkkn.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /exam-management/exam-timetable, +2 more
	{ prefix: '/api/master/semesters', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.exam_management.exam_timetables.view', 'page.master.semesters_myjkkn.view', 'page.users.learners_myjkkn.view'] },
	// /master/semesters
	{ prefix: '/api/master/semesters/*', exact: true, anyOf: ['page.master.semesters_myjkkn.view'] },
	// /exam-management/examination-sessions
	{ prefix: '/api/myjkkn/academic-years', exact: true, anyOf: ['page.exam_management.examination_sessions.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/edit, /course-management/course-offering, /course-management/course-offering/create, +21 more
	{ prefix: '/api/myjkkn/batches', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_attendance.view', 'page.exam_management.exam_types.view', 'page.exam_management.reports.attendance.view', 'page.grading.generate_final_marks.view', 'page.grading.grades.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.post_exam.external_mark_bulk_upload.view', 'page.pre_exam.hall_tickets.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.internal_mark_setting.view', 'page.pre_exam.mark_conversion_rules.view', 'page.reports.comprehensive.view', 'page.reports.marksheet_distribution.view', 'page.reports.semester_marksheet.view', 'page.test_myjkkn_api.view'] },
	// /test-myjkkn-api
	{ prefix: '/api/myjkkn/courses', exact: true, anyOf: ['page.test_myjkkn_api.view'] },
	// /test-myjkkn-api
	{ prefix: '/api/myjkkn/degrees', exact: true, anyOf: ['page.test_myjkkn_api.view'] },
	// /course-management/course-offering, /exam-management/exam-registrations, /exam-management/examination-sessions, /master/departments-myjkkn, +5 more
	{ prefix: '/api/myjkkn/departments', exact: true, anyOf: ['page.admin.role_management.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.examination_sessions.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.master.regulations_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.test_myjkkn_api.view'] },
	// /course-management/course-mapping/add, /course-management/course-mapping/edit, /course-management/course-offering, /grading/curriculum-grade-system, +3 more
	{ prefix: '/api/myjkkn/institutions', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.grading.grade_system.view', 'page.master.courses.view', 'page.test_myjkkn_api.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/edit, /course-management/course-offering, /course-management/course-offering/create, +38 more
	{ prefix: '/api/myjkkn/learner-profiles', exact: true, anyOf: ['page.admin.role_management.view', 'page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_applications.bulk.view', 'page.exam_management.exam_attendance.view', 'page.exam_management.exam_registrations.lookup.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.exam_types.view', 'page.exam_management.examination_sessions.view', 'page.exam_management.reports.attendance.view', 'page.grading.galley_report.report.view', 'page.grading.generate_final_marks.view', 'page.grading.grades.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.master.regulations_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.post_exam.external_mark_bulk_upload.view', 'page.pre_exam.hall_tickets.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.internal_mark_setting.view', 'page.pre_exam.mark_conversion_rules.view', 'page.reports.comprehensive.view', 'page.reports.marksheet_distribution.view', 'page.reports.nad.view', 'page.reports.semester_marksheet.view', 'page.result.dashboard.view', 'page.revaluation_management.view', 'page.test_myjkkn_api.view', 'page.users.generate_register_number.view', 'page.users.learners_myjkkn.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/edit, /course-management/course-offering, /course-management/course-offering/create, +20 more
	{ prefix: '/api/myjkkn/learners', exact: true, anyOf: ['page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_attendance.view', 'page.exam_management.exam_types.view', 'page.exam_management.reports.attendance.view', 'page.grading.generate_final_marks.view', 'page.grading.grades.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.post_exam.external_mark_bulk_upload.view', 'page.pre_exam.hall_tickets.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.internal_mark_setting.view', 'page.pre_exam.mark_conversion_rules.view', 'page.reports.comprehensive.view', 'page.reports.marksheet_distribution.view', 'page.reports.semester_marksheet.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /course-management/course-offering, +32 more
	{ prefix: '/api/myjkkn/programs', exact: true, anyOf: ['page.admin.role_management.view', 'page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_attendance.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.exam_types.view', 'page.exam_management.examination_sessions.view', 'page.exam_management.reports.attendance.view', 'page.exam_management.reports.course_count.view', 'page.grading.galley_report.report.view', 'page.grading.generate_final_marks.view', 'page.grading.grades.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.marks_management.comment_grades.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.master.regulations_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.post_exam.external_mark_bulk_upload.view', 'page.pre_exam.exam_attendance_sheet.view', 'page.pre_exam.hall_tickets.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.internal_mark_setting.view', 'page.pre_exam.mark_conversion_rules.view', 'page.reports.comprehensive.view', 'page.reports.marksheet_distribution.view', 'page.reports.nad.view', 'page.reports.semester_marksheet.view', 'page.result.dashboard.view', 'page.test_myjkkn_api.view'] },
	// /course-management/course-offering
	{ prefix: '/api/myjkkn/reference-cache', exact: true, anyOf: ['page.course_management.course_offering.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /course-management/course-offering, +33 more
	{ prefix: '/api/myjkkn/regulations', exact: true, anyOf: ['page.admin.role_management.view', 'page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_attendance.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.exam_types.view', 'page.exam_management.examination_sessions.view', 'page.exam_management.reports.attendance.view', 'page.grading.generate_final_marks.view', 'page.grading.grade_system.view', 'page.grading.grades.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.master.courses.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.master.regulations_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.post_exam.external_mark_bulk_upload.view', 'page.pre_exam.hall_tickets.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.internal_mark_setting.view', 'page.pre_exam.mark_conversion_rules.view', 'page.reports.comprehensive.view', 'page.reports.marksheet_distribution.view', 'page.reports.semester_marksheet.view', 'page.test_myjkkn_api.view'] },
	// /course-management/course-mapping, /course-management/course-mapping/add, /course-management/course-mapping/edit, /course-management/course-offering, +29 more
	{ prefix: '/api/myjkkn/semesters', exact: true, anyOf: ['page.admin.role_management.view', 'page.course_management.course_mapping_index.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_attendance.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.exam_types.view', 'page.exam_management.examination_sessions.view', 'page.exam_management.reports.attendance.view', 'page.grading.generate_final_marks.view', 'page.grading.grades.view', 'page.grading.learner_backlogs.view', 'page.grading.semester_results.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.master.regulations_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.post_exam.external_mark_bulk_upload.view', 'page.pre_exam.hall_tickets.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.internal_mark_setting.view', 'page.pre_exam.mark_conversion_rules.view', 'page.reports.comprehensive.view', 'page.reports.marksheet_distribution.view', 'page.reports.semester_marksheet.view', 'page.test_myjkkn_api.view'] },
	// /course-management/course-offering, /exam-management/exam-registrations, /exam-management/examination-sessions, /master/departments-myjkkn, +5 more
	{ prefix: '/api/myjkkn/staff', exact: true, anyOf: ['page.admin.role_management.view', 'page.course_management.course_offering.view', 'page.exam_management.exam_registrations.view', 'page.exam_management.examination_sessions.view', 'page.master.departments_myjkkn.view', 'page.master.programs_myjkkn.view', 'page.master.regulations_myjkkn.view', 'page.master.semesters_myjkkn.view', 'page.test_myjkkn_api.view'] },
	// /test-myjkkn-api
	{ prefix: '/api/myjkkn/students', exact: true, anyOf: ['page.test_myjkkn_api.view'] },
	// /master/pdf-settings, /master/pdf-settings/add, /master/pdf-settings/edit/[id], /pre-exam/examiner-allotment, +2 more
	{ prefix: '/api/pdf-settings', exact: true, methods: ['GET'], anyOf: ['page.master.pdf_settings.view', 'page.pre_exam.practical_allotment.view', 'page.reports.practical_exam.practical_need.view'] },
	// /master/pdf-settings, /master/pdf-settings/add, /master/pdf-settings/edit/[id], /master/pdf-settings/view/[id]
	{ prefix: '/api/pdf-settings/*', exact: true, methods: ['GET'], anyOf: ['page.master.pdf_settings.view'] },
	// /master/pdf-settings, /master/pdf-settings/add, /master/pdf-settings/edit/[id], /master/pdf-settings/view/[id]
	{ prefix: '/api/pdf-settings/preview', exact: true, methods: ['GET'], anyOf: ['page.master.pdf_settings.view'] },
	// /post-exam/result-release
	{ prefix: '/api/post-exam', exact: true, anyOf: ['page.grading.semester_results.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/answer-sheet-packets', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/answer-sheet-packets/*', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/answer-sheet-packets/generate-packets', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/answer-sheet-packets/generate-packets-program-wise', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/answer-sheet-packets/programs-by-registration', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/answer-sheet-packets, /post-exam/external-mark-entry, /post-exam/foil-sheet-download
	{ prefix: '/api/post-exam/bundle-numbers', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view', 'page.post_exam.external_mark_entry.view', 'page.post_exam.foil_sheet_download.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/bundle-numbers/*', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/answer-sheet-packets
	{ prefix: '/api/post-exam/bundle-numbers/generate', exact: true, anyOf: ['page.post_exam.answer_sheet_packets.view'] },
	// /post-exam/central-valuation/examiner
	{ prefix: '/api/post-exam/central-valuation/allotment', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/dates
	{ prefix: '/api/post-exam/central-valuation/board-windows', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/dates, /post-exam/central-valuation/email, /post-exam/central-valuation/examiner, /reports/cv-report
	{ prefix: '/api/post-exam/central-valuation/boards', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view', 'page.reports.cv_report.view'] },
	// /post-exam/central-valuation/dates
	{ prefix: '/api/post-exam/central-valuation/course-dates', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/email
	{ prefix: '/api/post-exam/central-valuation/email/assignments', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/email
	{ prefix: '/api/post-exam/central-valuation/email/pdf-preview', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/email
	{ prefix: '/api/post-exam/central-valuation/email/send', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/examiner
	{ prefix: '/api/post-exam/central-valuation/examiner-search', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/central-valuation/examiner
	{ prefix: '/api/post-exam/central-valuation/staff-search', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view'] },
	// /post-exam/exam-attendance-bulk
	{ prefix: '/api/post-exam/exam-attendance-bulk', exact: true, anyOf: ['page.post_exam.exam_attendance_bulk.view'] },
	// /post-exam/external-mark-entry
	{ prefix: '/api/post-exam/external-marks', exact: true, anyOf: ['page.post_exam.external_mark_entry.view'] },
	// /post-exam/external-mark-bulk-upload
	{ prefix: '/api/post-exam/external-marks-bulk', exact: true, anyOf: ['page.post_exam.external_mark_bulk_upload.view'] },
	// /post-exam/external-mark-correction
	{ prefix: '/api/post-exam/external-marks-correction', exact: true, anyOf: ['page.post_exam.external_mark_correction.view'] },
	// /post-exam/foil-sheet-download
	{ prefix: '/api/post-exam/foil-sheet-download', exact: true, anyOf: ['page.post_exam.foil_sheet_download.view'] },
	// /post-exam/practical-mark-entry
	{ prefix: '/api/post-exam/practical-marks', exact: true, anyOf: ['page.post_exam.practical_mark_entry.view'] },
	// /pre-exam/batch-allotment, /pre-exam/practical-allotment/batch
	{ prefix: '/api/pre-exam/batch-allotment', exact: true, anyOf: ['page.pre_exam.practical_allotment.view'] },
	// /pre-exam/cia-marks-entry, /pre-exam/internal-mark-entry, /pre-exam/internal-mark-entry-setting, /pre-exam/question-papers
	{ prefix: '/api/pre-exam/cia-entry-settings', exact: true, anyOf: ['page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.question_papers.view'] },
	// /pre-exam/internal-mark-entry-setting
	{ prefix: '/api/pre-exam/cia-entry-settings/*/fetch-attendance', exact: true, anyOf: ['page.pre_exam.internal_mark_entry_setting.view'] },
	// /pre-exam/internal-mark-entry-setting
	{ prefix: '/api/pre-exam/cia-entry-settings/*/timetable', exact: true, anyOf: ['page.pre_exam.internal_mark_entry_setting.view'] },
	// /pre-exam/internal-mark-entry-setting
	{ prefix: '/api/pre-exam/cia-entry-settings/*/timetable/scope', exact: true, anyOf: ['page.pre_exam.internal_mark_entry_setting.view'] },
	// /pre-exam/cia-marks-entry
	{ prefix: '/api/pre-exam/cia-marks', exact: true, anyOf: ['page.pre_exam.internal_mark_entry.view'] },
	// /pre-exam/cia-marks-entry
	{ prefix: '/api/pre-exam/cia-marks/*/lock', exact: true, anyOf: ['page.pre_exam.internal_mark_entry.view'] },
	// /pre-exam/question-papers
	{ prefix: '/api/pre-exam/course-outcomes', exact: true, anyOf: ['page.pre_exam.question_papers.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/ese-question-papers/*/answer-key-pdf', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/ese-question-papers/*/image', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/ese-question-papers/*/pdf', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/exam-attendance-sheet
	{ prefix: '/api/pre-exam/exam-attendance-sheet', exact: true, anyOf: ['page.pre_exam.exam_attendance_sheet.view'] },
	// /pre-exam/exam-attendance-sheet
	{ prefix: '/api/pre-exam/exam-attendance-sheet/batches', exact: true, anyOf: ['page.pre_exam.exam_attendance_sheet.view'] },
	// /pre-exam/exam-attendance-sheet
	{ prefix: '/api/pre-exam/exam-attendance-sheet/course-sheets', exact: true, anyOf: ['page.pre_exam.exam_attendance_sheet.view'] },
	// /pre-exam/exam-attendance-sheet
	{ prefix: '/api/pre-exam/exam-attendance-sheet/dates', exact: true, anyOf: ['page.pre_exam.exam_attendance_sheet.view'] },
	// /pre-exam/exam-attendance-sheet
	{ prefix: '/api/pre-exam/exam-attendance-sheet/sessions', exact: true, anyOf: ['page.pre_exam.exam_attendance_sheet.view'] },
	// /post-exam/central-valuation/dates, /post-exam/central-valuation/email, /post-exam/central-valuation/examiner, /pre-exam/examiner-allotment, +4 more
	{ prefix: '/api/pre-exam/examiner-allotment', exact: true, anyOf: ['page.post_exam.central_valuation.dates.view', 'page.pre_exam.practical_allotment.view', 'page.reports.cv_report.view'] },
	// /pre-exam/generate-internal-marks
	{ prefix: '/api/pre-exam/generate-internal-marks', exact: true, anyOf: ['page.pre_exam.generate_internal_marks.view'] },
	// /pre-exam/hall-tickets
	{ prefix: '/api/pre-exam/hall-tickets', exact: true, anyOf: ['page.pre_exam.hall_tickets.view'] },
	// /pre-exam/hall-tickets
	{ prefix: '/api/pre-exam/hall-tickets/semesters', exact: true, anyOf: ['page.pre_exam.hall_tickets.view'] },
	// /pre-exam/hall-tickets
	{ prefix: '/api/pre-exam/hall-tickets/students', exact: true, anyOf: ['page.pre_exam.hall_tickets.view'] },
	// /pre-exam/generate-internal-marks, /pre-exam/internal-mark-entry, /pre-exam/internal-mark-report, /pre-exam/question-papers
	{ prefix: '/api/pre-exam/internal-mark-entry', exact: true, anyOf: ['page.pre_exam.generate_internal_marks.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.question_papers.view'] },
	// /pre-exam/internal-mark-report
	{ prefix: '/api/pre-exam/internal-mark-report', exact: true, anyOf: ['page.pre_exam.internal_mark_report.view'] },
	// /pre-exam/bulk-internal-marks, /pre-exam/generate-internal-marks, /pre-exam/internal-mark-entry, /pre-exam/internal-mark-entry-setting, +5 more
	{ prefix: '/api/pre-exam/internal-marks', exact: true, anyOf: ['page.pre_exam.bulk_internal_marks.view', 'page.pre_exam.generate_internal_marks.view', 'page.pre_exam.internal_mark_entry.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.internal_mark_report.view', 'page.pre_exam.mark_conversion_rules.view', 'page.pre_exam.qp_examiner_assignment.view', 'page.pre_exam.question_paper_templates.view', 'page.pre_exam.question_papers.view'] },
	// /pre-exam/generate-internal-marks, /pre-exam/internal-mark-entry-setting, /pre-exam/mark-conversion-rules
	{ prefix: '/api/pre-exam/mark-conversion-rules', exact: true, anyOf: ['page.pre_exam.generate_internal_marks.view', 'page.pre_exam.internal_mark_entry_setting.view', 'page.pre_exam.mark_conversion_rules.view'] },
	// /pre-exam/practical-allotment/email, /pre-exam/practical-email
	{ prefix: '/api/pre-exam/practical-email/assignments', exact: true, anyOf: ['page.pre_exam.practical_allotment.view'] },
	// /pre-exam/practical-allotment/email, /pre-exam/practical-email
	{ prefix: '/api/pre-exam/practical-email/pdf-preview', exact: true, anyOf: ['page.pre_exam.practical_allotment.view'] },
	// /pre-exam/practical-allotment/email, /pre-exam/practical-email
	{ prefix: '/api/pre-exam/practical-email/send', exact: true, anyOf: ['page.pre_exam.practical_allotment.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/qp-examiner-assignments/courses', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/qp-examiner-assignments/examiners', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/qp-examiner-assignments/papers', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/qp-examiner-assignment
	{ prefix: '/api/pre-exam/qp-examiner-assignments/sessions', exact: true, anyOf: ['page.pre_exam.qp_examiner_assignment.view'] },
	// /pre-exam/question-paper-templates, /pre-exam/question-papers
	{ prefix: '/api/pre-exam/question-paper-templates', exact: true, anyOf: ['page.pre_exam.question_paper_templates.view', 'page.pre_exam.question_papers.view'] },
	// /pre-exam/question-paper-templates
	{ prefix: '/api/pre-exam/question-paper-templates/copy', exact: true, anyOf: ['page.pre_exam.question_paper_templates.view'] },
	// /pre-exam/question-papers
	{ prefix: '/api/pre-exam/question-papers', exact: true, anyOf: ['page.pre_exam.question_papers.view'] },
	// /pre-exam/question-papers
	{ prefix: '/api/pre-exam/question-papers/*', exact: true, anyOf: ['page.pre_exam.question_papers.view'] },
	// /pre-exam/question-papers
	{ prefix: '/api/pre-exam/question-papers/*/pdf', exact: true, anyOf: ['page.pre_exam.question_papers.view'] },
	// /pre-exam/question-paper-templates
	{ prefix: '/api/pre-exam/question-types', exact: true, anyOf: ['page.pre_exam.question_paper_templates.view'] },
	// /reports/dummy-numbers
	{ prefix: '/api/reports/answer-sheet-packets', exact: true, anyOf: ['page.reports.dummy_numbers.view'] },
	// /reports/practical-exam/practical-need
	{ prefix: '/api/reports/central-valuation/lunch-requirement', exact: true, anyOf: ['page.reports.practical_exam.practical_need.view'] },
	// /reports/comprehensive
	{ prefix: '/api/reports/comprehensive', exact: true, anyOf: ['page.reports.comprehensive.view'] },
	// /grading/consolidated-marksheet, /reports/consolidated-marksheet, /reports/consolidated-marksheet/[folio]
	{ prefix: '/api/reports/consolidated-marksheet', exact: true, anyOf: ['page.grading.semester_results.view', 'page.reports.semester_marksheet.view'] },
	// /reports/cv-report
	{ prefix: '/api/reports/cv-report/examiner-valuation', exact: true, anyOf: ['page.reports.cv_report.view'] },
	// /reports/cv-report
	{ prefix: '/api/reports/cv-report/panel-of-examiners', exact: true, anyOf: ['page.reports.cv_report.view'] },
	// /reports/cv-report
	{ prefix: '/api/reports/cv-report/pass-percentage', exact: true, anyOf: ['page.reports.cv_report.view'] },
	// /reports/dummy-numbers
	{ prefix: '/api/reports/dummy-numbers/filter-options', exact: true, anyOf: ['page.reports.dummy_numbers.view'] },
	// /exam-management/exam-registration-final-approval, /reports/exam-registration-reports
	{ prefix: '/api/reports/exam-registration-reports', exact: true, anyOf: ['page.exam_management.exam_registration_final_approval.view', 'page.reports.exam_registration_reports.view'] },
	// /reports/marksheet-distribution
	{ prefix: '/api/reports/marksheet-distribution', exact: true, anyOf: ['page.reports.marksheet_distribution.view'] },
	// /reports/exam-registration-reports
	{ prefix: '/api/reports/marksheet-distribution/programs', exact: true, anyOf: ['page.reports.exam_registration_reports.view'] },
	// /reports/practical-exam/practical-need
	{ prefix: '/api/reports/practical-exam/lunch-requirement', exact: true, anyOf: ['page.reports.practical_exam.practical_need.view'] },
	// /reports/semester-marksheet
	{ prefix: '/api/reports/semester-marksheet', exact: true, anyOf: ['page.reports.semester_marksheet.view'] },
	// /result/dashboard
	{ prefix: '/api/result-analytics/college-stats', exact: true, anyOf: ['page.result.dashboard.view'] },
	// /result/dashboard
	{ prefix: '/api/result-analytics/filter-options', exact: true, anyOf: ['page.result.dashboard.view'] },
	// /result/dashboard
	{ prefix: '/api/result-analytics/naac-reports', exact: true, anyOf: ['page.result.dashboard.view'] },
	// /reports/nad
	{ prefix: '/api/result-analytics/nad-csv-export', exact: true, anyOf: ['page.reports.nad.view'] },
	// /reports/nad
	{ prefix: '/api/result-analytics/nad-pivot-export', exact: true, anyOf: ['page.reports.nad.view'] },
	// /result/dashboard
	{ prefix: '/api/result-analytics/program-stats', exact: true, anyOf: ['page.result.dashboard.view'] },
	// /result/dashboard
	{ prefix: '/api/result-analytics/subject-stats', exact: true, anyOf: ['page.result.dashboard.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/assignments', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/draft-applications', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/fee-config', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/payment-status', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/publish', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management/create, /revaluation-management/periods
	{ prefix: '/api/revaluation/registration-periods', exact: true, anyOf: ['page.revaluation_management.create.view', 'page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/registrations', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/registrations/*', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management
	{ prefix: '/api/revaluation/student-eligibility', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /revaluation-management/create
	{ prefix: '/api/revaluation/types', exact: true, anyOf: ['page.revaluation_management.view'] },
	// /master/pdf-settings/add, /master/pdf-settings/edit/[id]
	{ prefix: '/api/upload/logo', exact: true, anyOf: ['page.master.pdf_settings.view'] },
	// /exam-management/exam-registrations, /exam-management/exam-registrations/lookup, /users/learners-list
	{ prefix: '/api/users/learners', exact: true, anyOf: ['page.exam_management.exam_registrations.lookup.view', 'page.exam_management.exam_registrations.view', 'page.users.learners_myjkkn.view'] },
	// /users/permissions, /users/permissions/add, /users/permissions/edit/[id], /users/role-permissions
	{ prefix: '/api/users/permissions', exact: true, methods: ['GET'], anyOf: ['page.users.permissions.view', 'page.users.role_permissions.view'] },
	// /users/permissions, /users/permissions/edit/[id]
	{ prefix: '/api/users/permissions/*', exact: true, methods: ['GET'], anyOf: ['page.users.permissions.view'] },
	// /users/role-permissions
	{ prefix: '/api/users/role-permissions', exact: true, methods: ['GET'], anyOf: ['page.users.role_permissions.view'] },
	// /users/role-permissions, /users/roles, /users/roles/add, /users/roles/edit/[id], +2 more
	{ prefix: '/api/users/roles', exact: true, methods: ['GET'], anyOf: ['page.admin.role_management.view', 'page.users.role_permissions.view', 'page.users.roles.view'] },
	// /users/roles, /users/roles/edit/[id]
	{ prefix: '/api/users/roles/*', exact: true, methods: ['GET'], anyOf: ['page.users.roles.view'] },
	// /users/user-roles, /users/users-list
	{ prefix: '/api/users/users-list', exact: true, methods: ['GET'], anyOf: ['page.admin.role_management.view'] },
	// /users/learners-list, /users/user-roles, /users/users-list
	{ prefix: '/api/users/users-list/*', exact: true, methods: ['GET'], anyOf: ['page.admin.role_management.view', 'page.users.learners_myjkkn.view'] },
	// /users/learners-list, /users/users-list
	{ prefix: '/api/users/users-list/*/roles', exact: true, methods: ['GET'], anyOf: ['page.admin.role_management.view', 'page.users.learners_myjkkn.view'] },
	// /reports/dummy-numbers, /utilities/dummy-numbers
	{ prefix: '/api/utilities/dummy-numbers', exact: true, anyOf: ['page.reports.dummy_numbers.view', 'page.utilities.dummy_numbers.view'] },
	// /utilities/dummy-numbers
	{ prefix: '/api/utilities/dummy-numbers/filter-options', exact: true, anyOf: ['page.utilities.dummy_numbers.view'] },
	// /utilities/dummy-numbers
	{ prefix: '/api/utilities/dummy-numbers/generate', exact: true, anyOf: ['page.utilities.dummy_numbers.view'] },
	// /utilities/dummy-numbers
	{ prefix: '/api/utilities/dummy-numbers/missing', exact: true, anyOf: ['page.utilities.dummy_numbers.view'] },
	// /utilities/dummy-numbers
	{ prefix: '/api/utilities/dummy-numbers/registration-count', exact: true, anyOf: ['page.utilities.dummy_numbers.view'] },
	// /reports/consolidated-marksheet, /reports/consolidated-marksheet/[folio], /reports/semester-marksheet
	{ prefix: '/api/utils/image-to-base64', exact: true, anyOf: ['page.reports.semester_marksheet.view'] },
]
